import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Montserrat } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "CEP Search",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat", // Variável CSS para esta fonte
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`antialiased  ${montserrat.variable}`}>
      <body
        className={` font-sans antialiased h-dvh flex flex-col items-center bg-[url('./pngtree-urban-city-map-town-street-png-image_5987385.png')] bg-cover bg-center bg-no-repeat`}
      >
        {children}
      </body>
    </html>
  );
}
